version: "3.9"

services:
  db:
    image: mysql:5.7
    volumes:
      - /home/pierre/Documents/TP/docker6-compose-Filtox/volumes/db/db_client:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - /home/pierre/Documents/TP/docker6-compose-Filtox/volumes/wordpress/wordpress_data_client:/var/www/html
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
